---
- hosts: all
  gather_facts: no
  become: true
  vars_files:
   variables.yaml
  tasks:
    - name: Install HTTP Server
      yum:
        name: httpd
        state: latest
    - name: Copy index.html
      template:
        src: index.html
        dest: /var/www/html/index.html
    - name: Start HTTP Server
      service:
        name: httpd
        state: started
...